### ISSUE TITLE
Could I get the name "octolearn"?

### ISSUE THREAD

**Issue by Simsal** [taroom/octolearn#1]
Hey @taroom ,

I'd like to start a project and I thought about naming it octolearn. As we can see, you were 5 years earlier :)

Do you still work on it? If not, would it be possible for you to rename your project? Would be really helpful for me.

Kind regards!

**Comment by taroom** [comment]
yes.. you can use that name.. i hope your project will be successful broo.. :) 
thank you for contacting me

warm greetings from Indonesia :)

**Comment by Simsal** [comment]
Thank you very much mate!

greetings from Germany and happy Coding!
